-- alias plug.spec 
---- Extend the `vim.pack.Spec` type with additional fields
---@class PlugSpec
---@field [1]? string|vim.pack.Spec|vim.pack shorthand for `src`
---@field build? string|fun(): nil
---@field config? fun(): nil
---@field dependencies? (string|vim.pack.Spec|PlugSpec)[]
---@field event? vim.api.keyset.events|vim.api.keyset.events[]
---@field enabled? boolean|fun():boolean
---@field specs? (string|vim.pack.Spec|PlugSpec)[]

