#!/bin/bash
#
## Add git submodules to the repository

set -euo pipefail
# set -x

VIM_DIR="${HOME}/.vim"
PACKDIR="${VIM_DIR}/pack/vimfect/opt"

if [[ ! -d "$PACKDIR" ]]; then
	mkdir -p "$PACKDIR"
fi

add_submodule() {
	local url="$1"
	
	cd "$PACKDIR" || { echo "Could not change to $PACKDIR"; exit 1; }

	git submodule add --force --depth 1 --progress "$url"
}

while [[ $# -gt 0 ]]; do
	add_submodule "$1"
	shift
done

add_submodule https://github.com/vim/killersheep
