---@meta
error('this file should not be required directly')

nv.blink = require('nvim.blink')
nv.keys = require('nvim.keys')
nv.lsp = require('nvim.lsp')
nv.treesitter = require('nvim.treesitter')

-- TODO: write an appropriate gen script for this
nv.debug = require('nvim.util.debug')
nv.echoserver = require('nvim.util.echoserver')
nv.exec = require('nvim.util.exec')
nv.external = require('nvim.util.external')
nv.file = require('nvim.util.file')
nv.formatter = require('nvim.util.formatter')
nv.gen = require('nvim.util.gen')
nv.git = require('nvim.util.git')
nv.icons = require('nvim.util.icons')
nv.json = require('nvim.util.json')
nv.mason = require('nvim.util.mason')
nv.module = require('nvim.util.module')
nv.munchies = require('nvim.util.munchies')
nv.notify = require('nvim.util.notify')
nv.patch = require('nvim.util.patch')
nv.path = require('nvim.util.path')
nv.root = require('nvim.util.root')
nv.snippets = require('nvim.util.snippets')
nv.status = require('nvim.util.status')
nv.submodules = require('nvim.util.submodules')
nv.tmuxline = require('nvim.util.tmuxline')
nv.track = require('nvim.util.track')
nv.wget = require('nvim.util.wget')
