--- @meta
error('this file should not be required directly')

nv.blink = require('nvim.blink')
nv.lsp = require('nvim.lsp')
nv.mini = require('nvim.mini')
nv.oil = require('nvim.oil')
nv.plug = require('nvim.plug')
nv.snacks = require('nvim.snacks')
nv.treesitter = require('nvim.treesitter')
nv.ui = require('nvim.ui')
nv.util = require('nvim.util')
nv.copilot = require('nvim.copilot')
-- nv.diagnostic = require('nvim.diagnostic')
nv.dial = require('nvim.dial')
nv.icons = require('nvim.icons')
nv.flash = require('nvim.flash')
nv.mason = require('nvim.lsp.mason')
nv.md = require('nvim.render-markdown')
nv.notify = require('nvim.notify')
nv.oil = require('nvim.oil')
nv.r = require('nvim.r')
nv.todo = require('nvim.todo-comments')
nv.tokyonight = require('nvim.tokyonight')
nv.wk = require('nvim.which-key')
