-- This file is generated. Do not edit.
---@meta
error('this file should not be required directly')

nv = require('nvim.util')
nv.git = require('nvim.git')
nv.git.extmarks = require('nvim.git.extmarks')
nv.git.meta = require('nvim.git.meta')
nv.keys.brackets = require('nvim.keys.brackets')
nv.keys.cmp = require('nvim.keys.cmp')
nv.keys.coerce = require('nvim.keys.coerce')
nv.keys.descriptions = require('nvim.keys.descriptions')
nv.keys.external = require('nvim.keys.external')
nv.keys.flash = require('nvim.keys.flash')
nv.keys.screen = require('nvim.keys.screen')
nv.keys.textobjects = require('nvim.keys.textobjects')
nv.keys.toggles = require('nvim.keys.toggles')
nv.keys.which = require('nvim.keys.which')
nv.lsp.progress = require('nvim.lsp.progress')
nv.mini.opts = require('nvim.mini.opts')
nv.tokyonight = require('nvim.tokyonight')
nv.tokyonight.extras = require('nvim.tokyonight.extras')
nv.tokyonight.lazy = require('nvim.tokyonight.lazy')
nv.tokyonight.opts = require('nvim.tokyonight.opts')
nv.tokyonight.plugins = require('nvim.tokyonight.plugins')
nv.tokyonight.scheme = require('nvim.tokyonight.scheme')
nv.treesitter.parsers = require('nvim.treesitter.parsers')
nv.treesitter.textobjects = require('nvim.treesitter.textobjects')
nv.ui = require('nvim.ui')
nv.ui['2'] = require('nvim.ui.2')
nv.ui.hl_groups = require('nvim.ui.hl_groups')
nv.ui.icons = require('nvim.ui.icons')
nv.ui.notify = require('nvim.ui.notify')
nv.ui.select = require('nvim.ui.select')
nv.ui.status = require('nvim.ui.status')
nv.ui.winbar = require('nvim.ui.winbar')
nv.util = require('nvim.util')
