-- This file is generated. Do not edit.
---@meta
error('this file should not be required directly')

nv = nv or {}
nv.keys = require('nvim.keys')
nv.keys.brackets = require('nvim.keys.brackets')
nv.keys.cmp = require('nvim.keys.cmp')
nv.keys.coerce = require('nvim.keys.coerce')
nv.keys.descriptions = require('nvim.keys.descriptions')
nv.keys.external = require('nvim.keys.external')
nv.keys.flash = require('nvim.keys.flash')
nv.keys.screen = require('nvim.keys.screen')
nv.keys.textobjects = require('nvim.keys.textobjects')
nv.keys.toggles = require('nvim.keys.toggles')
nv.lsp.groups = require('nvim.lsp.groups')
nv.lsp.progress = require('nvim.lsp.progress')
nv.mini = require('nvim.mini')
nv.mini.opts = require('nvim.mini.opts')
nv.status = require('nvim.status')
nv.tokyonight = require('nvim.tokyonight')
nv.tokyonight.extras = require('nvim.tokyonight.extras')
nv.tokyonight.lazy = require('nvim.tokyonight.lazy')
nv.tokyonight.opts = require('nvim.tokyonight.opts')
nv.tokyonight.plugins = require('nvim.tokyonight.plugins')
nv.tokyonight.scheme = require('nvim.tokyonight.scheme')
nv.treesitter.groups = require('nvim.treesitter.groups')
nv.treesitter.parsers = require('nvim.treesitter.parsers')
nv.treesitter.textobjects = require('nvim.treesitter.textobjects')
nv.ui = require('nvim.ui')
nv.ui["2"] = require('nvim.ui.2')
nv.ui.icons = require('nvim.ui.icons')
nv.ui.notify = require('nvim.ui.notify')
nv.ui.select = require('nvim.ui.select')
nv.util = require('nvim.util')
nv.util.file = require('nvim.util.file')
nv.util.git = require('nvim.util.git')
nv.util.git.extmarks = require('nvim.util.git.extmarks')
nv.util.git.meta = require('nvim.util.git.meta')
