local groups = {
  -- ['ALEErrorSign'] = { fg = '#db4b4b' },
  -- ['ALEWarningSign'] = { fg = '#e0af68' },
  ['Bold'] = { bold = true, fg = '#c0caf5' },
  ['Character'] = { fg = '#39ff14' },
  -- ['ColorColumn'] = { bg = '#000000' },
  ['ColorColumn'] = { bg = '#27a1b9' },
  ['Comment'] = { fg = '#565f89', italic = true },
  ['ComplHint'] = { fg = '#414868' },
  ['Conceal'] = { fg = '#737aa2' },
  ['Constant'] = { fg = '#ff9e64' },
  ['CurSearch'] = { link = 'IncSearch' },
  -- cursor
  ['Cursor'] = { bg = '#c0caf5', fg = '#1a1b26' },
  ['CursorColumn'] = { bg = '#292e42' },
  ['CursorIM'] = { bg = '#c0caf5', fg = '#1a1b26' },
  ['CursorLine'] = { bg = '#292e42' },
  ['CursorLineNr'] = { bold = true, fg = '#ff9e64' },
  ['Debug'] = { fg = '#ff9e64' },
  ['Delimiter'] = { link = 'Special' },
  -- diff
  ['DiffAdd'] = { bg = '#243e4a' },
  ['DiffChange'] = { bg = '#1f2231' },
  ['DiffDelete'] = { bg = '#4a272f' },
  ['DiffText'] = { bg = '#394b70' },
  ['Directory'] = { fg = '#14afff' },
  ['EndOfBuffer'] = { fg = '#1a1b26' },
  ['Error'] = { fg = '#db4b4b' },
  ['ErrorMsg'] = { fg = '#db4b4b' },
  ['FloatBorder'] = { bg = 'NONE', fg = '#27a1b9' },
  ['FloatTitle'] = { bg = 'NONE', fg = '#27a1b9' },
  ['FoldColumn'] = { bg = 'NONE', fg = '#565f89' },
  ['Folded'] = { bg = '#3b4261', fg = '#14afff' },
  ['Foo'] = { bg = '#ff007c', fg = '#c0caf5' },
  ['Function'] = { fg = '#14afff' },
  ['Identifier'] = { fg = '#bb9af7', italic = false },
  ['IncSearch'] = { bg = '#ff9e64', fg = '#000000' },
  ['Italic'] = { fg = '#c0caf5', italic = true },
  ['Keyword'] = { bold = true, fg = '#7dcfff', italic = false },
  ['LineNr'] = { fg = '#3b4261' },
  ['LineNrAbove'] = { fg = '#3b4261' },
  ['LineNrBelow'] = { fg = '#3b4261' },
  ['MatchParen'] = { bold = true, fg = '#ff9e64' },
  ['ModeMsg'] = { bold = true, fg = '#a9b1d6' },
  ['MoreMsg'] = { fg = '#14afff' },
  ['MsgArea'] = { fg = '#a9b1d6' },
  ['NonText'] = { fg = '#545c7e' },
  ['Normal'] = { bg = 'NONE', fg = '#c0caf5' },
  ['NormalFloat'] = { bg = 'NONE', fg = '#c0caf5' },
  ['NormalNC'] = { bg = 'NONE', fg = '#c0caf5' },
  ['NormalSB'] = { bg = 'NONE', fg = '#a9b1d6' },
  ['Number'] = { fg = '#14afff' },
  ['Operator'] = { fg = '#89ddff' },
  ['Pmenu'] = { bg = '#16161e', fg = '#c0caf5' },
  ['PmenuMatch'] = { bg = '#16161e', fg = '#2ac3de' },
  ['PmenuMatchSel'] = { bg = '#343a55', fg = '#2ac3de' },
  ['PmenuSbar'] = { bg = '#1f1f29' },
  ['PmenuSel'] = { bg = '#343a55' },
  ['PmenuThumb'] = { bg = '#3b4261' },
  ['PreProc'] = { fg = '#7dcfff' },
  ['Question'] = { fg = '#14afff' },
  ['QuickFixLine'] = { bg = '#283457', bold = true },
  ['Search'] = { bg = '#3d59a1', fg = '#c0caf5' },
  ['SignColumn'] = { bg = 'NONE', fg = '#3b4261' },
  ['SignColumnSB'] = { bg = 'NONE', fg = '#3b4261' },
  ['Special'] = { bold = true, fg = '#f7768e' },
  ['SpecialKey'] = { fg = '#545c7e' },
  ['SpellBad'] = { bg = '#f7768e' },
  ['SpellCap'] = { sp = '#e0af68', undercurl = true },
  ['SpellLocal'] = { sp = '#0db9d7', undercurl = true },
  ['SpellRare'] = { sp = '#1abc9c', undercurl = true },
  ['Statement'] = { fg = '#bb9af7' },
  ['StatusLine'] = { bg = 'NONE' },
  ['StatusLineNC'] = { bg = '#16161e', fg = '#3b4261' },
  ['String'] = { fg = '#39ff14' },
  ['Substitute'] = { bg = '#f7768e', fg = '#000000' },
  ['TabLine'] = { bg = '#16161e', fg = '#3b4261' },
  ['TabLineFill'] = { bg = 'NONE' },
  ['TabLineSel'] = { bg = '#14afff', fg = '#000000' },
  ['Title'] = { bold = true, fg = '#14afff' },
  -- ['Todo'] = { bg = '#e0af68', fg = '#1a1b26' },
  -- ['TreesitterContext'] = { bg = '#343a55' },
  ['Type'] = { fg = '#2ac3de' },
  ['Underlined'] = { underline = true },
  ['VertSplit'] = { fg = '#15161e' },
  ['Visual'] = { bg = '#283457' },
  ['VisualNOS'] = { bg = '#283457' },
  ['WarningMsg'] = { fg = '#e0af68' },
  ['Whitespace'] = { fg = '#3b4261' },
  ['WildMenu'] = { bg = '#283457' },
  ['WinSeparator'] = { bold = true, fg = '#15161e' },

  -- nvim
  ['DiagnosticError'] = { fg = '#db4b4b' },
  ['DiagnosticHint'] = { fg = '#1abc9c' },
  ['DiagnosticInfo'] = { fg = '#0db9d7' },
  ['DiagnosticWarn'] = { fg = '#e0af68' },
  ['DiagnosticVirtualTextError'] = { bg = '#2d202a', fg = '#db4b4b' },
  ['DiagnosticVirtualTextHint'] = { bg = '#1a2b32', fg = '#1abc9c' },
  ['DiagnosticVirtualTextInfo'] = { bg = '#192b38', fg = '#0db9d7' },
  ['DiagnosticVirtualTextWarn'] = { bg = '#2e2a2d', fg = '#e0af68' },
  ['DiagnosticUnnecessary'] = { fg = '#414868' },
  ['WinBar'] = { link = 'StatusLine' },
  ['WinBarNC'] = { link = 'StatusLineNC' },

  ['debugBreakpoint'] = { bg = '#192b38', fg = '#0db9d7' },
  ['debugPC'] = { bg = 'NONE' },

  ['diffAdded'] = { bg = '#243e4a', fg = '#449dab' },
  ['diffChanged'] = { bg = '#1f2231', fg = '#6183bb' },
  ['diffFile'] = { fg = '#14afff' },
  ['diffIndexLine'] = { fg = '#bb9af7' },
  ['diffLine'] = { fg = '#565f89' },
  ['diffNewFile'] = { bg = '#243e4a', fg = '#2ac3de' },
  ['diffOldFile'] = { bg = '#4a272f', fg = '#2ac3de' },
  ['diffRemoved'] = { bg = '#4a272f', fg = '#914c54' },

  ['dosIniLabel'] = { link = '@property' },

  ['healthError'] = { fg = '#db4b4b' },
  ['healthSuccess'] = { fg = '#73daca' },
  ['healthWarning'] = { fg = '#e0af68' },

  ['helpCommand'] = { bg = '#414868', fg = '#14afff' },
  ['helpExample'] = { fg = '#565f89' },

  ['htmlH1'] = { bold = true, fg = '#bb9af7' },
  ['htmlH2'] = { bold = true, fg = '#14afff' },

  ['lCursor'] = { bg = '#c0caf5', fg = '#1a1b26' },

  ['qfFileName'] = { fg = '#14afff' },
  ['qfLineNr'] = { fg = '#737aa2' },
}

local ts = require('nvim.treesitter.groups')
groups = vim.tbl_deep_extend('keep', groups, ts)

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
