local groups = {
  -- ['ALEErrorSign'] = { fg = '#db4b4b' },
  -- ['ALEWarningSign'] = { fg = '#e0af68' },
  ['Bold'] = { bold = true, fg = '#c0caf5' },
  ['Character'] = { fg = '#39ff14' },
  ['ColorColumn'] = { bg = '#000000' },
  ['Comment'] = { fg = '#565f89', italic = true },
  ['ComplHint'] = { fg = '#414868' },
  ['Conceal'] = { fg = '#737aa2' },
  ['Constant'] = { fg = '#ff9e64' },
  ['CurSearch'] = { link = 'IncSearch' },
  -- cursor
  ['Cursor'] = { bg = '#c0caf5', fg = '#1a1b26' },
  ['CursorColumn'] = { bg = '#292e42' },
  ['CursorIM'] = { bg = '#c0caf5', fg = '#1a1b26' },
  ['CursorLine'] = { bg = '#292e42' },
  ['CursorLineNr'] = { bold = true, fg = '#ff9e64' },
  ['Debug'] = { fg = '#ff9e64' },
  ['Delimiter'] = { link = 'Special' },
  -- diagnostic
  ['DiagnosticError'] = { fg = '#db4b4b' },
  ['DiagnosticHint'] = { fg = '#1abc9c' },
  ['DiagnosticInfo'] = { fg = '#0db9d7' },
  ['DiagnosticUnderlineError'] = { sp = '#db4b4b', undercurl = true },
  ['DiagnosticUnderlineHint'] = { sp = '#1abc9c', undercurl = true },
  ['DiagnosticUnderlineInfo'] = { sp = '#0db9d7', undercurl = true },
  ['DiagnosticUnderlineWarn'] = { sp = '#e0af68', undercurl = true },
  ['DiagnosticUnnecessary'] = { fg = '#414868' },
  ['DiagnosticVirtualTextError'] = { bg = '#2d202a', fg = '#db4b4b' },
  ['DiagnosticVirtualTextHint'] = { bg = '#1a2b32', fg = '#1abc9c' },
  ['DiagnosticVirtualTextInfo'] = { bg = '#192b38', fg = '#0db9d7' },
  ['DiagnosticVirtualTextWarn'] = { bg = '#2e2a2d', fg = '#e0af68' },
  ['DiagnosticWarn'] = { fg = '#e0af68' },
  -- diff
  ['DiffAdd'] = { bg = '#243e4a' },
  ['DiffChange'] = { bg = '#1f2231' },
  ['DiffDelete'] = { bg = '#4a272f' },
  ['DiffText'] = { bg = '#394b70' },
  ['Directory'] = { fg = '#14afff' },
  ['EndOfBuffer'] = { fg = '#1a1b26' },
  ['Error'] = { fg = '#db4b4b' },
  ['ErrorMsg'] = { fg = '#db4b4b' },
  ['FloatBorder'] = { bg = 'NONE', fg = '#27a1b9' },
  ['FloatTitle'] = { bg = 'NONE', fg = '#27a1b9' },
  ['FoldColumn'] = { bg = 'NONE', fg = '#565f89' },
  ['Folded'] = { bg = '#3b4261', fg = '#14afff' },
  ['Foo'] = { bg = '#ff007c', fg = '#c0caf5' },
  ['Function'] = { fg = '#14afff' },
  ['Identifier'] = { fg = '#bb9af7', italic = false },
  ['IncSearch'] = { bg = '#ff9e64', fg = '#000000' },
  ['Italic'] = { fg = '#c0caf5', italic = true },
  ['Keyword'] = { bold = true, fg = '#7dcfff', italic = false },
  ['LineNr'] = { fg = '#3b4261' },
  ['LineNrAbove'] = { fg = '#3b4261' },
  ['LineNrBelow'] = { fg = '#3b4261' },
  ['LspCodeLens'] = { fg = '#565f89' },
  ['LspInfoBorder'] = { bg = 'NONE', fg = '#27a1b9' },
  ['LspInlayHint'] = { bg = '#1d202d', fg = '#545c7e' },
  ['LspKindArray'] = { link = '@punctuation.bracket' },
  ['LspKindBoolean'] = { link = '@boolean' },
  ['LspKindClass'] = { link = '@type' },
  ['LspKindColor'] = { link = 'Special' },
  ['LspKindConstant'] = { link = '@constant' },
  ['LspKindConstructor'] = { link = '@constructor' },
  ['LspKindEnum'] = { link = '@lsp.type.enum' },
  ['LspKindEnumMember'] = { link = '@lsp.type.enumMember' },
  ['LspKindEvent'] = { link = 'Special' },
  ['LspKindField'] = { link = '@variable.member' },
  ['LspKindFile'] = { link = 'Normal' },
  ['LspKindFolder'] = { link = 'Directory' },
  ['LspKindFunction'] = { link = '@function' },
  ['LspKindInterface'] = { link = '@lsp.type.interface' },
  ['LspKindKey'] = { link = '@variable.member' },
  ['LspKindKeyword'] = { link = '@lsp.type.keyword' },
  ['LspKindMethod'] = { link = '@function.method' },
  ['LspKindModule'] = { link = '@module' },
  ['LspKindNamespace'] = { link = '@module' },
  ['LspKindNull'] = { link = '@constant.builtin' },
  ['LspKindNumber'] = { link = '@number' },
  ['LspKindObject'] = { link = '@constant' },
  ['LspKindOperator'] = { link = '@operator' },
  ['LspKindPackage'] = { link = '@module' },
  ['LspKindProperty'] = { link = '@property' },
  ['LspKindReference'] = { link = '@markup.link' },
  ['LspKindSnippet'] = { link = 'Conceal' },
  ['LspKindString'] = { link = '@string' },
  ['LspKindStruct'] = { link = '@lsp.type.struct' },
  ['LspKindText'] = { link = '@markup' },
  ['LspKindTypeParameter'] = { link = '@lsp.type.typeParameter' },
  ['LspKindUnit'] = { link = '@lsp.type.struct' },
  ['LspKindValue'] = { link = '@string' },
  ['LspKindVariable'] = { link = '@variable' },
  ['LspReferenceRead'] = { bg = '#3b4261' },
  ['LspReferenceText'] = { bg = '#3b4261' },
  ['LspReferenceWrite'] = { bg = '#3b4261' },
  ['LspSignatureActiveParameter'] = { bg = '#20253a', bold = true },
  ['MatchParen'] = { bold = true, fg = '#ff9e64' },
  ['MiniDiffOverAdd'] = { link = 'DiffAdd' },
  ['MiniDiffOverChange'] = { link = 'DiffText' },
  ['MiniDiffOverContext'] = { link = 'DiffChange' },
  ['MiniDiffOverDelete'] = { link = 'DiffDelete' },
  ['MiniDiffSignAdd'] = { fg = '#449dab' },
  ['MiniDiffSignChange'] = { fg = '#6183bb' },
  ['MiniDiffSignDelete'] = { fg = '#914c54' },
  ['MiniFilesBorder'] = { link = 'FloatBorder' },
  ['MiniFilesBorderModified'] = { link = 'DiagnosticFloatingWarn' },
  ['MiniFilesCursorLine'] = { link = 'CursorLine' },
  ['MiniFilesDirectory'] = { link = 'Directory' },
  ['MiniFilesFile'] = { fg = '#c0caf5' },
  ['MiniFilesNormal'] = { link = 'NormalFloat' },
  ['MiniFilesTitle'] = { link = 'FloatTitle' },
  ['MiniFilesTitleFocused'] = { bg = 'NONE', bold = true, fg = '#27a1b9' },
  ['MiniHipatternsFixme'] = { bg = '#db4b4b', bold = true, fg = '#000000' },
  ['MiniHipatternsHack'] = { bg = '#e0af68', bold = true, fg = '#000000' },
  ['MiniHipatternsNote'] = { bg = '#1abc9c', bold = true, fg = '#000000' },
  ['MiniHipatternsTodo'] = { bg = '#0db9d7', bold = true, fg = '#000000' },
  ['MiniIconsAzure'] = { fg = '#0db9d7' },
  ['MiniIconsBlue'] = { fg = '#14afff' },
  ['MiniIconsCyan'] = { fg = '#1abc9c' },
  ['MiniIconsGreen'] = { fg = '#39ff14' },
  ['MiniIconsGrey'] = { fg = '#c0caf5' },
  ['MiniIconsOrange'] = { fg = '#ff9e64' },
  ['MiniIconsPurple'] = { fg = '#9d7cd8' },
  ['MiniIconsRed'] = { fg = '#f7768e' },
  ['MiniIconsYellow'] = { fg = '#e0af68' },
  ['MiniSurround'] = { bg = '#ff9e64', fg = '#000000' },
  ['ModeMsg'] = { bold = true, fg = '#a9b1d6' },
  ['MoreMsg'] = { fg = '#14afff' },
  ['MsgArea'] = { fg = '#a9b1d6' },
  ['NonText'] = { fg = '#545c7e' },
  ['Normal'] = { bg = 'NONE', fg = '#c0caf5' },
  ['NormalFloat'] = { bg = 'NONE', fg = '#c0caf5' },
  ['NormalNC'] = { bg = 'NONE', fg = '#c0caf5' },
  ['NormalSB'] = { bg = 'NONE', fg = '#a9b1d6' },
  ['Number'] = { fg = '#14afff' },
  ['Operator'] = { fg = '#89ddff' },
  ['Pmenu'] = { bg = '#16161e', fg = '#c0caf5' },
  ['PmenuMatch'] = { bg = '#16161e', fg = '#2ac3de' },
  ['PmenuMatchSel'] = { bg = '#343a55', fg = '#2ac3de' },
  ['PmenuSbar'] = { bg = '#1f1f29' },
  ['PmenuSel'] = { bg = '#343a55' },
  ['PmenuThumb'] = { bg = '#3b4261' },
  ['PreProc'] = { fg = '#7dcfff' },
  ['Question'] = { fg = '#14afff' },
  ['QuickFixLine'] = { bg = '#283457', bold = true },
  ['RenderMarkdownBullet'] = { fg = '#ff9e64' },
  ['RenderMarkdownCode'] = { bg = '#16161e' },
  ['RenderMarkdownCodeInline'] = { link = '@markup.raw.markdown_inline' },
  ['RenderMarkdownDash'] = { fg = '#ff9e64' },
  ['RenderMarkdownH1Bg'] = { bg = '#24293b' },
  ['RenderMarkdownH1Fg'] = { bold = true, fg = '#7aa2f7' },
  ['RenderMarkdownH2Bg'] = { bg = '#2e2a2d' },
  ['RenderMarkdownH2Fg'] = { bold = true, fg = '#e0af68' },
  ['RenderMarkdownH3Bg'] = { bg = '#272d2d' },
  ['RenderMarkdownH3Fg'] = { bold = true, fg = '#9ece6a' },
  ['RenderMarkdownH4Bg'] = { bg = '#1a2b32' },
  ['RenderMarkdownH4Fg'] = { bold = true, fg = '#1abc9c' },
  ['RenderMarkdownH5Bg'] = { bg = '#2a283b' },
  ['RenderMarkdownH5Fg'] = { bold = true, fg = '#bb9af7' },
  ['RenderMarkdownH6Bg'] = { bg = '#272538' },
  ['RenderMarkdownH6Fg'] = { bold = true, fg = '#9d7cd8' },
  ['RenderMarkdownH7Bg'] = { bg = '#31282c' },
  ['RenderMarkdownH7Fg'] = { bold = true, fg = '#ff9e64' },
  ['RenderMarkdownH8Bg'] = { bg = '#302430' },
  ['RenderMarkdownH8Fg'] = { bold = true, fg = '#f7768e' },
  ['RenderMarkdownTableHead'] = { fg = '#f7768e' },
  ['RenderMarkdownTableRow'] = { fg = '#ff9e64' },
  ['Search'] = { bg = '#3d59a1', fg = '#c0caf5' },
  -- ['SidekickDiffAdd'] = { link = 'DiffAdd' },
  -- ['SidekickDiffContext'] = { link = 'DiffChange' },
  -- ['SidekickDiffDelete'] = { link = 'DiffDelete' },
  -- ['SidekickSignAdd'] = { fg = '#449dab' },
  -- ['SidekickSignChange'] = { fg = '#6183bb' },
  -- ['SidekickSignDelete'] = { fg = '#914c54' },
  ['SignColumn'] = { bg = 'NONE', fg = '#3b4261' },
  ['SignColumnSB'] = { bg = 'NONE', fg = '#3b4261' },
  ['Special'] = { bold = true, fg = '#f7768e' },
  ['SpecialKey'] = { fg = '#545c7e' },
  ['SpellBad'] = { bg = '#f7768e' },
  ['SpellCap'] = { sp = '#e0af68', undercurl = true },
  ['SpellLocal'] = { sp = '#0db9d7', undercurl = true },
  ['SpellRare'] = { sp = '#1abc9c', undercurl = true },
  ['Statement'] = { fg = '#bb9af7' },
  ['StatusLine'] = { bg = 'NONE' },
  ['StatusLineNC'] = { bg = '#16161e', fg = '#3b4261' },
  ['String'] = { fg = '#39ff14' },
  ['Substitute'] = { bg = '#f7768e', fg = '#000000' },
  ['TabLine'] = { bg = '#16161e', fg = '#3b4261' },
  ['TabLineFill'] = { bg = 'NONE' },
  ['TabLineSel'] = { bg = '#14afff', fg = '#000000' },
  ['Title'] = { bold = true, fg = '#14afff' },
  ['Todo'] = { bg = '#e0af68', fg = '#1a1b26' },
  -- ['TreesitterContext'] = { bg = '#343a55' },
  ['Type'] = { fg = '#2ac3de' },
  ['Underlined'] = { underline = true },
  ['VertSplit'] = { fg = '#15161e' },
  ['Visual'] = { bg = '#283457' },
  ['VisualNOS'] = { bg = '#283457' },
  ['WarningMsg'] = { fg = '#e0af68' },
  -- ['WhichKey'] = { fg = '#7dcfff' },
  -- ['WhichKeyDesc'] = { fg = '#bb9af7' },
  -- ['WhichKeyGroup'] = { fg = '#14afff' },
  -- ['WhichKeyNormal'] = { bg = 'NONE' },
  -- ['WhichKeySeparator'] = { fg = '#565f89' },
  -- ['WhichKeyValue'] = { fg = '#737aa2' },
  ['Whitespace'] = { fg = '#3b4261' },
  ['WildMenu'] = { bg = '#283457' },
  ['WinSeparator'] = { bold = true, fg = '#15161e' },
  -- nvim 
  ['WinBar'] = { link = 'StatusLine' },
  ['WinBarNC'] = { link = 'StatusLineNC' },
  ['debugBreakpoint'] = { bg = '#192b38', fg = '#0db9d7' },
  ['debugPC'] = { bg = 'NONE' },
  ['diffAdded'] = { bg = '#243e4a', fg = '#449dab' },
  ['diffChanged'] = { bg = '#1f2231', fg = '#6183bb' },
  ['diffFile'] = { fg = '#14afff' },
  ['diffIndexLine'] = { fg = '#bb9af7' },
  ['diffLine'] = { fg = '#565f89' },
  ['diffNewFile'] = { bg = '#243e4a', fg = '#2ac3de' },
  ['diffOldFile'] = { bg = '#4a272f', fg = '#2ac3de' },
  ['diffRemoved'] = { bg = '#4a272f', fg = '#914c54' },
  ['dosIniLabel'] = { link = '@property' },
  ['healthError'] = { fg = '#db4b4b' },
  ['healthSuccess'] = { fg = '#73daca' },
  ['healthWarning'] = { fg = '#e0af68' },
  ['helpCommand'] = { bg = '#414868', fg = '#14afff' },
  ['helpExample'] = { fg = '#565f89' },
  ['htmlH1'] = { bold = true, fg = '#bb9af7' },
  ['htmlH2'] = { bold = true, fg = '#14afff' },
  ['lCursor'] = { bg = '#c0caf5', fg = '#1a1b26' },
  ['qfFileName'] = { fg = '#14afff' },
  ['qfLineNr'] = { fg = '#737aa2' },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
