#!/usr/bin/env bash

indent="          "

cd -P -- "$(dirname "$0")" || exit 1
 
{
	fortune ./tips/vimtips | cowsay | sed "s/^/$indent/"
	printf "\n"
	cat << 'EOF'
  The computing scientist's main challenge is not to get
      confused by the complexities of his own making.
EOF
} | lolcat
