-- see `:h treesitter-highlight`
return {
  ['@annotation'] = { link = 'PreProc' },
  ['@attribute'] = { link = 'PreProc' },
  ['@boolean'] = { link = 'Boolean' },
  ['@character'] = { link = 'Character' },
  ['@character.printf'] = { link = 'SpecialChar' },
  ['@character.special'] = { link = 'SpecialChar' },
  ['@comment'] = { link = 'Comment' },
  ['@comment.error'] = { fg = '#db4b4b' },
  ['@comment.hint'] = { fg = '#1abc9c' },
  ['@comment.info'] = { fg = '#0db9d7' },
  ['@comment.note'] = { fg = '#1abc9c' },
  ['@comment.todo'] = { fg = '#7aa2f7' },
  ['@comment.warning'] = { fg = '#e0af68' },
  ['@constant'] = { link = 'Constant' },
  ['@constant.builtin'] = { link = 'Special' },
  ['@constant.macro'] = { link = 'Define' },
  ['@constructor'] = { fg = '#bb9af7' },
  ['@constructor.tsx'] = { fg = '#2ac3de' },
  ['@diff.delta'] = { link = 'DiffChange' },
  ['@diff.minus'] = { link = 'DiffDelete' },
  ['@diff.plus'] = { link = 'DiffAdd' },
  ['@function'] = { link = 'Function' },
  ['@function.builtin'] = { link = 'Special' },
  ['@function.call'] = { link = '@function' },
  ['@function.macro'] = { link = 'Macro' },
  ['@function.method'] = { link = 'Function' },
  ['@function.method.call'] = { link = '@function.method' },
  ['@keyword'] = { bold = true, fg = '#9d7cd8', italic = false },
  ['@keyword.conditional'] = { link = 'Conditional' },
  ['@keyword.coroutine'] = { link = '@keyword' },
  ['@keyword.debug'] = { link = 'Debug' },
  ['@keyword.directive'] = { link = 'PreProc' },
  ['@keyword.directive.define'] = { link = 'Define' },
  ['@keyword.exception'] = { link = 'Exception' },
  ['@keyword.function'] = { fg = '#bb9af7' },
  ['@keyword.import'] = { link = 'Include' },
  ['@keyword.operator'] = { link = '@operator' },
  ['@keyword.repeat'] = { link = 'Repeat' },
  ['@keyword.return'] = { link = '@keyword' },
  ['@keyword.storage'] = { link = 'StorageClass' },
  ['@label'] = { fg = '#14afff' },
  ['@lsp.type.boolean'] = { link = '@boolean' },
  ['@lsp.type.builtinType'] = { link = '@type.builtin' },
  ['@lsp.type.comment'] = { link = '@comment' },
  ['@lsp.type.decorator'] = { link = '@attribute' },
  ['@lsp.type.deriveHelper'] = { link = '@attribute' },
  ['@lsp.type.enum'] = { link = '@type' },
  ['@lsp.type.enumMember'] = { link = '@constant' },
  ['@lsp.type.escapeSequence'] = { link = '@string.escape' },
  ['@lsp.type.formatSpecifier'] = { link = '@markup.list' },
  ['@lsp.type.generic'] = { link = '@variable' },
  ['@lsp.type.interface'] = { fg = '#57c5e5' },
  ['@lsp.type.keyword'] = { link = '@keyword' },
  ['@lsp.type.lifetime'] = { link = '@keyword.storage' },
  ['@lsp.type.namespace'] = { link = '@module' },
  ['@lsp.type.namespace.python'] = { link = '@variable' },
  ['@lsp.type.number'] = { link = '@number' },
  ['@lsp.type.operator'] = { link = '@operator' },
  ['@lsp.type.parameter'] = { link = '@variable.parameter' },
  ['@lsp.type.property'] = { link = '@property' },
  ['@lsp.type.selfKeyword'] = { link = '@variable.builtin' },
  ['@lsp.type.selfTypeKeyword'] = { link = '@variable.builtin' },
  ['@lsp.type.string'] = { link = '@string' },
  ['@lsp.type.typeAlias'] = { link = '@type.definition' },
  ['@lsp.type.unresolvedReference'] = { sp = '#db4b4b', undercurl = true },
  ['@lsp.type.variable'] = {},
  ['@lsp.typemod.class.defaultLibrary'] = { link = '@type.builtin' },
  ['@lsp.typemod.enum.defaultLibrary'] = { link = '@type.builtin' },
  ['@lsp.typemod.enumMember.defaultLibrary'] = { link = '@constant.builtin' },
  ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
  ['@lsp.typemod.keyword.async'] = { link = '@keyword.coroutine' },
  ['@lsp.typemod.keyword.injected'] = { link = '@keyword' },
  ['@lsp.typemod.macro.defaultLibrary'] = { link = '@function.builtin' },
  ['@lsp.typemod.method.defaultLibrary'] = { link = '@function.builtin' },
  ['@lsp.typemod.operator.injected'] = { link = '@operator' },
  ['@lsp.typemod.string.injected'] = { link = '@string' },
  ['@lsp.typemod.struct.defaultLibrary'] = { link = '@type.builtin' },
  ['@lsp.typemod.type.defaultLibrary'] = { fg = '#27a1b9' },
  ['@lsp.typemod.typeAlias.defaultLibrary'] = { fg = '#27a1b9' },
  ['@lsp.typemod.variable.callable'] = { link = '@function' },
  ['@lsp.typemod.variable.defaultLibrary'] = { link = '@variable.builtin' },
  ['@lsp.typemod.variable.injected'] = { link = '@variable' },
  ['@lsp.typemod.variable.static'] = { link = '@constant' },
  ['@markup'] = { link = '@none' },
  ['@markup.emphasis'] = { italic = true },
  ['@markup.environment'] = { link = 'Macro' },
  ['@markup.environment.name'] = { link = 'Type' },
  ['@markup.heading'] = { link = 'Title' },
  ['@markup.heading.1.markdown'] = { bg = '#24293b', bold = true, fg = '#7aa2f7' },
  ['@markup.heading.2.markdown'] = { bg = '#2e2a2d', bold = true, fg = '#e0af68' },
  ['@markup.heading.3.markdown'] = { bg = '#272d2d', bold = true, fg = '#9ece6a' },
  ['@markup.heading.4.markdown'] = { bg = '#1a2b32', bold = true, fg = '#1abc9c' },
  ['@markup.heading.5.markdown'] = { bg = '#2a283b', bold = true, fg = '#bb9af7' },
  ['@markup.heading.6.markdown'] = { bg = '#272538', bold = true, fg = '#9d7cd8' },
  ['@markup.heading.7.markdown'] = { bg = '#31282c', bold = true, fg = '#ff9e64' },
  ['@markup.heading.8.markdown'] = { bg = '#302430', bold = true, fg = '#f7768e' },
  ['@markup.italic'] = { italic = true },
  ['@markup.link'] = { fg = '#1abc9c' },
  ['@markup.link.label'] = { link = 'SpecialChar' },
  ['@markup.link.label.symbol'] = { link = 'Identifier' },
  ['@markup.link.url'] = { link = 'Underlined' },
  ['@markup.list'] = { fg = '#89ddff' },
  ['@markup.list.checked'] = { fg = '#73daca' },
  ['@markup.list.markdown'] = { bold = true, fg = '#ff9e64' },
  ['@markup.list.unchecked'] = { fg = '#14afff' },
  ['@markup.math'] = { link = 'Special' },
  ['@markup.raw'] = { link = 'String' },
  ['@markup.raw.markdown_inline'] = { bg = '#414868', fg = '#14afff' },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.strong'] = { bold = true },
  ['@markup.underline'] = { underline = true },
  ['@module'] = { link = 'Include' },
  ['@module.builtin'] = { fg = '#f7768e' },
  ['@namespace.builtin'] = { link = '@variable.builtin' },
  ['@none'] = {},
  ['@number'] = { link = 'Number' },
  ['@number.float'] = { link = 'Float' },
  ['@operator'] = { fg = '#89ddff' },
  ['@property'] = { fg = '#73daca' },
  ['@punctuation.bracket'] = { fg = '#a9b1d6' },
  ['@punctuation.delimiter'] = { fg = '#89ddff' },
  ['@punctuation.special'] = { fg = '#89ddff' },
  ['@punctuation.special.markdown'] = { fg = '#ff9e64' },
  ['@string'] = { link = 'String' },
  ['@string.documentation'] = { fg = '#e0af68' },
  ['@string.escape'] = { fg = '#bb9af7' },
  ['@string.regexp'] = { fg = '#b4f9f8' },
  ['@tag'] = { link = 'Label' },
  ['@tag.attribute'] = { link = '@property' },
  ['@tag.delimiter'] = { link = 'Delimiter' },
  ['@tag.delimiter.tsx'] = { fg = '#1683be' },
  ['@tag.javascript'] = { fg = '#f7768e' },
  ['@tag.tsx'] = { fg = '#f7768e' },
  ['@type'] = { link = 'Type' },
  ['@type.builtin'] = { fg = '#27a1b9' },
  ['@type.definition'] = { link = 'Typedef' },
  ['@type.qualifier'] = { link = '@keyword' },
  ['@variable'] = { fg = '#c0caf5', italic = false },
  ['@variable.builtin'] = { fg = '#f7768e' },
  ['@variable.member'] = { fg = '#73daca' },
  ['@variable.parameter'] = { fg = '#e0af68' },
  ['@variable.parameter.builtin'] = { fg = '#dab484' },
}
