-- Table of parsers to automatically install with nvim-treesitter
-- NOTE: They still have to be manually enabled for most filetypes
-- see `<url>` for available parsers
return {
  'lua',
  'vim',
  -- 'asm',
  'bash',
  -- 'bibtex',
  -- 'csv',
  'cmake',
  'cpp',
  'cuda',
  'comment', -- HACK: this is a custom parser
  'diff',
  'dockerfile',
  'doxygen',
  'git_config',
  'gitcommit',
  'git_rebase',
  'gitattributes',
  'gitignore',
  'gitcommit',
  -- 'groovy',
  'html',
  'javascript',
  'jsdoc',
  'json',
  'jsonc',
  -- 'json5',
  'latex',
  'llvm',
  'luadoc',
  'luap',
  'make',
  'ocaml',
  'printf',
  'python',
  'regex',
  'r',
  'rnoweb',
  'toml',
  'xml',
  'yaml',
}
